### ISSUE TITLE
XP tally not able to award xp

### ISSUE THREAD

**Issue by Avitale34** [teroparvinen/foundry-xp-tally#2]
When I click the award XP button normally I would get a pop up but i am getting this error and nothing happens.

![image](https://github.com/teroparvinen/foundry-xp-tally/assets/65961637/595336a8-4511-461d-a49e-918ae03edc9c)

**Comment by teroparvinen** [comment]
This was probably caused by having deleted an actor that was previously included in the xp award. A fix is out now. Thanks for the report!
